# Generated by Django 6.0.6 on 2026-09-25 06:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('commander', 'Commander'), ('duel', 'Duel Commander')], default='commander', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('seed', models.BigIntegerField()),
                ('max_rounds', models.PositiveIntegerField(default=20)),
                ('round', models.PositiveIntegerField(default=0)),
                ('end_reason', models.CharField(blank=True, choices=[('last_standing', 'Last player standing'), ('turn_limit', 'Round limit reached')], default='', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('deck_name', models.CharField(max_length=255)),
                ('agent', models.CharField(choices=[('random', 'Random'), ('llm', 'LLM')], default='random', max_length=16)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('life', models.IntegerField(blank=True, null=True)),
                ('eliminated_round', models.PositiveIntegerField(blank=True, null=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='decks.deck')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='playtest.match')),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='playtest.seat'),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('round', models.PositiveIntegerField()),
                ('turn', models.PositiveIntegerField()),
                ('seat_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='playtest.match')),
            ],
            options={
                'db_table': 'match_events',
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('match', 'seq'), name='unique_event_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('match', 'position'), name='unique_seat_position'),
        ),
    ]
