# Generated by Django 6.0.6 on 2026-06-30 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('raw_decklist', models.TextField()),
                ('analysis_md', models.TextField(blank=True, null=True)),
                ('deck_type', models.CharField(default='Custom', max_length=64)),
                ('total_cards', models.IntegerField(default=0)),
                ('total_value_eur', models.FloatField(default=0.0)),
                ('avg_cmc', models.FloatField(default=0.0)),
                ('category_counts', models.JSONField(default=dict)),
                ('cards', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'decks',
            },
        ),
        migrations.CreateModel(
            name='ScryfallCard',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'scryfall_cards',
            },
        ),
        migrations.CreateModel(
            name='ScryfallImage',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'scryfall_images',
            },
        ),
    ]
