# Generated by Django 6.0.6 on 2026-06-30 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_deck_analyzer', '0002_deck_status_error'),
    ]

    # The integer primary key has no meaningful UUID equivalent, so we drop it
    # and add a fresh UUID id. Existing rows keep their data but get new ids.
    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='id',
        ),
        migrations.AddField(
            model_name='deck',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
