# Generated by Django 6.0.6 on 2026-09-19 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_deck_analyzer', '0008_deck_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_decklist', models.TextField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='mtg_deck_analyzer.deck')),
            ],
            options={
                'db_table': 'deck_versions',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
