# Generated by Django 6.0.6 on 2026-09-19 16:30

from django.db import migrations


def backfill_legacy_versions(apps, schema_editor):
    """Gives every pre-existing deck a first ``DeckVersion``.

    ``DeckVersion`` (0008) only started being written going forward: a deck
    submitted before that migration has no rows in its history. Without this
    backfill, that deck's *next* edit would create a version that wrongly
    reads as "Initial version" (its changelog compares against nothing,
    hiding what was actually cut) instead of showing the real diff against
    the decklist the deck already had.

    Only decks with zero versions are touched, so running this twice (or
    after the app has already started writing versions for new decks) is a
    no-op the second time.
    """
    Deck = apps.get_model("mtg_deck_analyzer", "Deck")
    DeckVersion = apps.get_model("mtg_deck_analyzer", "DeckVersion")

    for deck in Deck.objects.filter(versions__isnull=True):
        DeckVersion.objects.create(
            deck=deck,
            raw_decklist=deck.raw_decklist,
            created_at=deck.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_deck_analyzer', '0009_deck_version'),
    ]

    operations = [
        migrations.RunPython(
            backfill_legacy_versions,
            # The backfilled rows are indistinguishable from real ones once
            # written, so the reverse deliberately leaves them in place
            # rather than guessing which versions to delete.
            reverse_code=migrations.RunPython.noop,
        ),
    ]
