# Generated by Django 6.0.6 on 2026-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_deck_analyzer', '0010_backfill_legacy_deck_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='bracket',
            field=models.JSONField(default=dict),
        ),
    ]
