# Generated by Django 6.0.6 on 2026-09-25 06:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScryfallCard',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'scryfall_cards',
            },
        ),
        migrations.CreateModel(
            name='ScryfallImage',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'scryfall_images',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('commander', 'Commander'), ('duel', 'Duel Commander')], default='commander', max_length=16)),
                ('raw_decklist', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Importing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('commander', models.CharField(blank=True, default='', max_length=255)),
                ('color_identity', models.JSONField(default=list)),
                ('cards', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decks',
                'ordering': ['-created_at'],
            },
        ),
    ]
